<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>RenewableFallenSticks</AssemblyName>
    <RootNamespace>RenewableFallenSticks</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="VintagestoryAPI">
      <HintPath>/Applications/Vintage Story.app/VintagestoryAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="VSSurvivalMod">
      <HintPath>/Applications/Vintage Story.app/Mods/VSSurvivalMod.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
